apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: 'https://github.com/your-username/your-repo'
        - name: revision
          value: main

    - name: build-image
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: 'docker.io/your-dockerhub-username/rails-app'

    - name: deploy
      taskRef:
        name: kubectl-apply
      params:
        - name: manifests
          value: 'path/to/kubernetes/manifests/*.yaml'
